
name: SecurityChecks

on:
  push:
    branches: [ "main", "develop", "vulnerabilities_scaner"]
  pull_request:
    branches: [ "main" ]

jobs:

  security_checks:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [ "3.7" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run code vulnerabilities analysis
        run: bandit -c common/tests/security/bandit/bandit.yaml -r .
