
name: SecurityChecks

on:
  push:
    branches: [ "main", "develop", "dev" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  security_checks:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [ "3.7" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # test our matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run code analysis tool
        run: bandit -c bandit.yaml -r . -f json -o results.json

      - name: Analyze results
        if: always()
        run: python check_results.py